#6

puts "When this function was called, two arguments weren't provided."